name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set environment
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: i18n validation (optional)
        run: npm run i18n:ci
        continue-on-error: true

      - name: i18n fail on [MISSING] in dist
        run: npm run i18n:postbuild:fail-on-missing
